# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:year/:month/:day/:title
future: true

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: pygments

# https://help.github.com/articles/migrating-your-pages-site-from-maruku
markdown: kramdown

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : CoderCamp
tagline: Hamilton's Unconference
description: "CoderCamp Hamilton is for local software developers to learn tools, techniques, and technologies from one another in a casual and friendly setting."
author :
  name : CoderCamp Hamilton
  email : codercamphamilton@gmail.com
  github : codercamp
  twitter : Codercamp
#  feedburner : feedname