# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /Events/:year/:month/:day/:title

# Shows events with dates in the future
future: true

exclude: [".gitignore", "CNAME", "README.md", "Gemfile"]
highlighter: pygments

# https://help.github.com/articles/migrating-your-pages-site-from-maruku
markdown: kramdown

title : CoderCamp
tagline: Hamilton's Unconference
description: "CoderCamp Hamilton is for local software developers to learn tools, techniques, and technologies from one another in a casual and friendly setting."
author :
  name : CoderCamp Hamilton
  email : codercamphamilton@gmail.com
  github : codercamp
  twitter : CoderCampHamont
#  feedburner : feedname

# This is used in the Atom & RSS feeds and in the sitemap
production_url: http://www.codercamphamilton.com
rss_path: /rss.xml
atom_path: /atom.xml
